# Change these first
owner: Sid220 # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Vestal
    url: https://vestal.tk
  - name: SmartDisplayPi Backend
    url: https://backend.sdp.vestal.tk
    expectedStatusCodes:
      - 200
      - 403
  - name: SmartDisplayPi Documentation
    url: https://docs.sdp.vestal.tk
  - name: Quotes API
    url: https://quotes.api.vestal.tk

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.vestal.tk
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Vestal
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
