# Change these first
owner: Sid220 # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Plios
    url: https://plios.tech
  - name: SmartDisplayPi Backend
    url: https://backend.sdp.plios.tech
    expectedStatusCodes:
      - 200
      - 403
  - name: SmartDisplayPi Documentation
    url: https://docs-sdp.plios.tech
  - name: Quotes API
    url: https://quotes-api.plios.tech
  - name: VirtualBox Icons for HTML Documentation
    url: https://vi.plios.tech
  - name: WinterWonderland
    url: https://winterwonderland.plios.tech

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.plios.tech
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Plios
  navbar:
    - title: Home
      href: https://plios.tech
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
